"""Audit which runs are missing retrieval evaluation.

Targets the FULL run matrix:
  - 8 baselines (lda, prodlda, ...) × 3 datasets × 4 K
  - 3 generative methods × 5 LLMs × 3 datasets × 4 K
Writes scripts/run_retrieval_missing.sh with one evaluate_retrieval.py call per
missing run, and prints a summary.
"""
import os
import sys
from collections import defaultdict
from dotenv import load_dotenv

load_dotenv('/home/toolkit/LLM-Topic-Modeling/.env')
import wandb

ENTITY = os.environ['WANDB_ENTITY']
DATASETS = ['20_newsgroups', 'tweet_topic', 'stackoverflow']

ALL_METHODS = ['generative', 'generative_ecrtm', 'generative_fastopic']
ALL_LLMS = [
    'ERNIE-4.5-0.3B-PT',
    'Llama-3.1-8B-Instruct',
    'Llama-3.2-1B-Instruct',
    'Phi-3-mini-128k-instruct',
    'Qwen3.5-0.8B',
]
BASELINES = ['lda', 'prodlda', 'zeroshot', 'combined', 'etm', 'bertopic', 'ecrtm', 'fastopic']
KS = [25, 50, 75, 100]

# Build expected run-name set: baselines + generative × LLM
expected_runs = set()  # (dataset, run_name)
for dataset in DATASETS:
    for m in BASELINES:
        for K in KS:
            expected_runs.add((dataset, f"{m}_K{K}"))
    for method in ALL_METHODS:
        for llm in ALL_LLMS:
            for K in KS:
                expected_runs.add((dataset, f"{method}_{llm}_K{K}"))

print(f"Expected target runs: {len(expected_runs)}", file=sys.stderr)


def quality(run):
    s = run.summary
    finished = 1 if run.state == 'finished' else 0
    has_cv = 1 if s.get('avg/cv_wiki') is not None else 0
    ari = s.get('avg/ari') or 0
    inv_purity = s.get('avg/inverse_purity')
    non_degenerate = 1 if (ari and ari > 0) else 0
    if inv_purity is not None and inv_purity >= 0.999 and (ari is None or ari == 0):
        non_degenerate = 0
    return (non_degenerate, finished, has_cv, ari)


def has_retrieval_artifact(run):
    """Mirrors evaluate_retrieval.has_retrieval_artifact."""
    try:
        for a in run.logged_artifacts():
            if a.type == 'evaluation' and 'retrieval' in a.name:
                return True
    except Exception:
        return False
    return False


api = wandb.Api(timeout=60)

# Group results: for each expected run, find best wandb run (or None)
best = {}  # (dataset, name) -> run
for dataset in DATASETS:
    project = f"{ENTITY}/{dataset}"
    print(f"Fetching {project}...", file=sys.stderr)
    runs = list(api.runs(project, per_page=500))
    for r in runs:
        key = (dataset, r.name)
        if key not in expected_runs:
            continue
        ex = best.get(key)
        if ex is None or quality(r) > quality(ex):
            best[key] = r

# Categorize
have_retrieval = []
need_retrieval = []
no_run = []
not_finished = []

print(f"\nChecking retrieval artifacts on {len(best)} candidate runs...", file=sys.stderr)
for key in expected_runs:
    run = best.get(key)
    if run is None:
        no_run.append(key)
        continue
    if run.state != 'finished':
        not_finished.append((key, run.state, run.id))
        continue
    if has_retrieval_artifact(run):
        have_retrieval.append((key, run.id))
    else:
        need_retrieval.append((key, run.id))

# Summary
print(f"\n{'='*70}")
print(f"RETRIEVAL EVALUATION AUDIT")
print(f"{'='*70}")
print(f"Total target runs:             {len(expected_runs)}")
print(f"  Have retrieval results:      {len(have_retrieval)}")
print(f"  Missing retrieval results:   {len(need_retrieval)}")
print(f"  Run not yet finished:        {len(not_finished)}")
print(f"  Run does not exist:          {len(no_run)}")

if need_retrieval:
    print(f"\n{'-'*70}")
    print(f"NEEDS RETRIEVAL ({len(need_retrieval)}):")
    print(f"{'-'*70}")
    by_proj = defaultdict(list)
    for (dataset, name), run_id in need_retrieval:
        by_proj[dataset].append((name, run_id))
    for proj in DATASETS:
        if proj in by_proj:
            print(f"\n[{proj}] ({len(by_proj[proj])} runs)")
            for name, run_id in sorted(by_proj[proj]):
                print(f"  {name:60s} id={run_id}")

if not_finished:
    print(f"\n{'-'*70}")
    print(f"NOT FINISHED — skip until done ({len(not_finished)}):")
    print(f"{'-'*70}")
    for (dataset, name), state, run_id in sorted(not_finished):
        print(f"  {dataset:18s} {name:55s} state={state}")

if no_run:
    print(f"\n{'-'*70}")
    print(f"NO RUN AT ALL ({len(no_run)}):")
    print(f"{'-'*70}")
    for dataset, name in sorted(no_run):
        print(f"  {dataset:18s} {name}")

# Write the bash script
out_path = '/home/toolkit/LLM-Topic-Modeling/scripts/run_retrieval_missing.sh'
with open(out_path, 'w') as f:
    f.write("#!/bin/bash\n")
    f.write("# Auto-generated by audit_retrieval.py\n")
    f.write("# Runs evaluate_retrieval.py for runs missing retrieval results,\n")
    f.write("# scoped to (new method ∪ new LLM): generative_{ecrtm,fastopic} OR Phi-3 / Qwen3.5.\n\n")
    f.write('PYTHON="/home/toolkit/.conda/envs/llm-topics/bin/python"\n')
    f.write('CUDA_VISIBLE_DEVICES=2\n')
    f.write('export CUDA_VISIBLE_DEVICES\n\n')
    by_proj = defaultdict(list)
    for (dataset, name), run_id in need_retrieval:
        by_proj[dataset].append((name, run_id))
    total = 0
    for proj in DATASETS:
        items = sorted(by_proj.get(proj, []))
        if not items:
            continue
        f.write(f"# === {proj} ({len(items)} runs) ===\n")
        for name, run_id in items:
            f.write(
                f'echo "[$(date +%H:%M:%S)] {proj} / {name}"\n'
                f'$PYTHON evaluate_retrieval.py --wandb_project {proj} --run_id_or_name {run_id}\n'
            )
            total += 1
        f.write("\n")
    f.write(f'echo "Done. {total} retrieval evaluations submitted."\n')

os.chmod(out_path, 0o755)
print(f"\nWrote {out_path} ({len(need_retrieval)} jobs)")
