#!/bin/bash
# Auto-generated by audit_retrieval.py
# Runs evaluate_retrieval.py for runs missing retrieval results,
# scoped to (new method ∪ new LLM): generative_{ecrtm,fastopic} OR Phi-3 / Qwen3.5.

PYTHON="/home/toolkit/.conda/envs/llm-topics/bin/python"
CUDA_VISIBLE_DEVICES=2
export CUDA_VISIBLE_DEVICES

# === 20_newsgroups (8 runs) ===
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_ERNIE-4.5-0.3B-PT_K100"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name s8kd9a43
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_ERNIE-4.5-0.3B-PT_K25"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name 9s8eensm
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_ERNIE-4.5-0.3B-PT_K50"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name rj7xdbwb
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_ERNIE-4.5-0.3B-PT_K75"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name m27s971v
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_fastopic_Qwen3.5-0.8B_K100"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name oq1uj9tp
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_fastopic_Qwen3.5-0.8B_K25"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name ugl2rpnw
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_fastopic_Qwen3.5-0.8B_K50"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name j63sjkdr
echo "[$(date +%H:%M:%S)] 20_newsgroups / generative_fastopic_Qwen3.5-0.8B_K75"
$PYTHON evaluate_retrieval.py --wandb_project 20_newsgroups --run_id_or_name 0o3kuo0q

# === tweet_topic (5 runs) ===
echo "[$(date +%H:%M:%S)] tweet_topic / generative_ERNIE-4.5-0.3B-PT_K100"
$PYTHON evaluate_retrieval.py --wandb_project tweet_topic --run_id_or_name yvzq8gxi
echo "[$(date +%H:%M:%S)] tweet_topic / generative_ERNIE-4.5-0.3B-PT_K25"
$PYTHON evaluate_retrieval.py --wandb_project tweet_topic --run_id_or_name tfzdtbbv
echo "[$(date +%H:%M:%S)] tweet_topic / generative_ERNIE-4.5-0.3B-PT_K50"
$PYTHON evaluate_retrieval.py --wandb_project tweet_topic --run_id_or_name aar9nrvv
echo "[$(date +%H:%M:%S)] tweet_topic / generative_ERNIE-4.5-0.3B-PT_K75"
$PYTHON evaluate_retrieval.py --wandb_project tweet_topic --run_id_or_name ommtrxup
echo "[$(date +%H:%M:%S)] tweet_topic / generative_fastopic_Llama-3.2-1B-Instruct_K100"
$PYTHON evaluate_retrieval.py --wandb_project tweet_topic --run_id_or_name pj0pbi9o

# === stackoverflow (4 runs) ===
echo "[$(date +%H:%M:%S)] stackoverflow / generative_ERNIE-4.5-0.3B-PT_K100"
$PYTHON evaluate_retrieval.py --wandb_project stackoverflow --run_id_or_name fx6i2ahj
echo "[$(date +%H:%M:%S)] stackoverflow / generative_ERNIE-4.5-0.3B-PT_K25"
$PYTHON evaluate_retrieval.py --wandb_project stackoverflow --run_id_or_name lmnyubd0
echo "[$(date +%H:%M:%S)] stackoverflow / generative_ERNIE-4.5-0.3B-PT_K50"
$PYTHON evaluate_retrieval.py --wandb_project stackoverflow --run_id_or_name h9yra8uu
echo "[$(date +%H:%M:%S)] stackoverflow / generative_ERNIE-4.5-0.3B-PT_K75"
$PYTHON evaluate_retrieval.py --wandb_project stackoverflow --run_id_or_name mmn3k9cq

echo "Done. 17 retrieval evaluations submitted."
